sonar.projectKey=Chetan-Lawate_Preordingfoodapp
sonar.organization=chetan-lawate
sonar.sources=backend,frontend
sonar.tests=backend
sonar.test.inclusions=backend/test_*.py
sonar.exclusions=**/__pycache__/**,**/*.pyc,frontend/static/**
sonar.coverage.exclusions=backend/models.py,backend/seed.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8